### ISSUE TITLE
Design inconsistencies team member overview page

### ISSUE THREAD

**Issue by boris-arkenaar** [humanoidsbv/team-awesome-naomi#31]
- [x] A team member 'row' has too much height. In the design they are less high.
- [x] The font sizes of the titles 'Team members' and '22 Humanoids' are not the same as in the design.
- [x] Try to place icons using css only. Making use of background and ::after (with content: ""), removing the svg element from your template.

**Comment by naomiaz** [comment]
Fix this in my latest branch #54
